steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'dies-per-wafer', '--trigger-http', '--no-gen2', '--source=.', '--region', 'us-west1', '--runtime', 'python310', '--entry-point', 'cloudFunctionEntrypoint']